# name: Create Release Tag

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'packages/fighting-design/package.json'

# jobs:
#   release-tag:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@master

#       - name: Create Release Tag
#         id: release_tag
#         uses: yyx990803/release-tag@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           body: |
#             详细更新日志请参考 [CHANGELOG.md](https://github.com/FightingDesign/fighting-design/blob/master/CHANGELOG.md)。

#             Please refer to [CHANGELOG.en-US.md](https://github.com/FightingDesign/fighting-design/blob/master/CHANGELOG.en-US.md) for details.
